version: ">= 2.0.0"
language: node_js
node_js:
- 12
before_install:
  - openssl aes-256-cbc -K $encrypted_afaae77f48e5_key -iv $encrypted_afaae77f48e5_iv
    -in firebaseauth.json.enc -out firebaseauth.json -d
  - openssl aes-256-cbc -K $encrypted_24ecaed9e146_key -iv $encrypted_24ecaed9e146_iv
    -in travisacckey.json.enc -out travisacckey.json -d
deploy:
  - provider: gae
    keyfile: travisacckey.json
    project: cardsagainsthodgkinson
    version: "$TRAVIS_BUILD_NUMBER"
    cleanup: false
    skip_cleanup: true
    promote: true
    on:
      branch: master
  - provider: gae
    keyfile: travisacckey.json
    project: cardsagainsthodgkinson
    version: "$TRAVIS_BUILD_NUMBER"
    cleanup: false
    skip_cleanup: true
    promote: false
    no_promote: true
    on:
      branch: beta

before_script:
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
